---
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Cluster size setup altered to allow console Query Editor to run
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a basic Redshift cluster
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Redshift Configuration
      Parameters:
      - MasterUsername
      - MasterUserPassword
      - PortNumber
      - DatabaseName
      - NumberOfNodes
      - NodeType
      - RedshiftIamCopyRoleArn
      - SageMakerSecurityGroup
      #- DesktopAccessIp
Parameters:
  DatabaseName:
    Description: The name of the first database to be created when the cluster is created
    Type: String
    Default: dev
    AllowedPattern: "([a-z]|[0-9])+"
  NumberOfNodes:
    Description: The number of compute nodes in the cluster. For multi-node clusters,
      the NumberOfNodes parameter must be greater than 1
    Type: Number
    MinValue: 2
    MaxValue: 32
    Default: 2
  NodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: ds2.8xlarge
    AllowedValues:
    - dc1.8xlarge
    - dc2.large
    - dc2.8xlarge
    - ds2.8xlarge
  MasterUsername:
    Description: The user name that is associated with the master user account for
      the cluster that is being created
    Type: String
    Default: masteruser
    AllowedPattern: "([a-z])([a-z]|[0-9])*"
  MasterUserPassword:
    Description: The password that is associated with the master user account for
      the cluster that is being created.
    MinLength: 8
    MaxLength: 64      
    Type: String
    NoEcho: 'true'
  PortNumber:
    Description: The port number on which the cluster accepts incoming connections.
    Type: Number
    Default: '5439'
  #DesktopAccessIp:
  #  Description: IP address for you to access Redshift from your SQL desktop program
  #  Type: String
  VPCId:
    Description: VPC in which to launch this stack
    Type: AWS::EC2::VPC::Id
  VPCSubnet:
    Description: Subnet in which to launch this stack 
    Type: AWS::EC2::Subnet::Id
  SageMakerSecurityGroup:
    Description: Security group SageMaker will be running in, to access Redshift
    Type: AWS::EC2::SecurityGroup::Id   
  S3Bucket:
    Description: S3 bucket for temp files, is cleaned as part of cleanup
    Type: String    
Conditions:
  IsOneNode:
    Fn::Equals:
    - Ref: NumberOfNodes
    - '1'
Resources:
  RedshiftIamCopyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - redshift.amazonaws.com
          Action: sts:AssumeRole
          Condition:
            StringLike:
              sts:ExternalId:
                Fn::Join:
                - ""
                - - 'arn:aws:redshift:'
                  - Ref: AWS::Region
                  - ':'
                  - Ref: AWS::AccountId
                  - ':dbuser:*/'
                  - Ref: MasterUsername
      Policies:
        - PolicyName: allowglue
          PolicyDocument:         
              Version: '2012-10-17'
              Statement:
                - Sid: p1
                  Effect: Allow
                  Action:
                  - glue:*
                  Resource: "*"
        - PolicyName: allows3
          PolicyDocument:         
              Version: '2012-10-17'
              Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:DeleteObjectVersion
                - s3:GetBucketLogging
                - s3:GetAccelerateConfiguration
                - s3:GetBucketPolicy
                - s3:GetBucketLocation
                - s3:GetObjectVersion
                - s3:List*
                Resource:
                - !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref S3Bucket
                - !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref S3Bucket                
                    - "/*"
              - Sid: VisualEditor1
                Effect: Allow
                Action:
                - s3:GetAccessPoint
                - s3:GetAccountPublicAccessBlock
                - s3:ListAccessPoints
                - s3:HeadBucket
                Resource:
                - !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref S3Bucket
    
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
      #- arn:aws:iam::aws:policy/AmazonAthenaFullAccess  
      - arn:aws:iam::aws:policy/AmazonRedshiftQueryEditor
      Path: "/"
  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Retain            # Glue ENIs may take a while to delete; and, will cause stack deletion to fail
    Properties:
      GroupDescription: Redshift security group
      SecurityGroupIngress:
      # This rule gives access to Redshift from the SageMaker notebook
      - FromPort:
          Ref: PortNumber
        ToPort:
          Ref: PortNumber
        IpProtocol: tcp
        SourceSecurityGroupId:
          Ref: SageMakerSecurityGroup
      # This rule gives access to Redshift from the user's desktop
      #- FromPort:   !Ref PortNumber
      #  ToPort:     !Ref PortNumber
      #  IpProtocol: tcp
      #  CidrIp: !Ref DesktopAccessIp         
      VpcId:
        Ref: VPCId
  RedshiftSecurityGroupIngress:   
    # This next rule gives access to Glue (and EMR, and the world)  
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      FromPort:  0
      ToPort: 65535
      IpProtocol: TCP
      GroupId: !Ref RedshiftSecurityGroup 
      #GroupName: String
      SourceSecurityGroupId: !Ref RedshiftSecurityGroup      
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    DependsOn:
    - RedshiftSecurityGroup
    DeletionPolicy: Delete
    Properties:
      ClusterType:
        Fn::If:
        - IsOneNode
        - single-node
        - multi-node
      NumberOfNodes:
        Fn::If:
        - IsOneNode
        - Ref: AWS::NoValue
        - Ref: NumberOfNodes
      NodeType:
        Ref: NodeType
      DBName:
        Ref: DatabaseName
      MasterUsername:
        Ref: MasterUsername
      MasterUserPassword:
        Ref: MasterUserPassword
      IamRoles: 
        - Fn::GetAtt:
          - RedshiftIamCopyRole
          - Arn
      VpcSecurityGroupIds:
      - Ref: RedshiftSecurityGroup
      PubliclyAccessible: 'true'
      Port:
        Ref: PortNumber
Outputs:
  RedshiftClusterEndpoint:
    Description: Redshift cluster endpoint, used for client access
    Value:
      Fn::Join:
      - ":"
      - - Fn::GetAtt:
          - RedshiftCluster
          - Endpoint.Address
        - Fn::GetAtt:
          - RedshiftCluster
          - Endpoint.Port
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RedshiftClusterEndpoint"
  RedshiftClusterName:
    Description: Redshift cluster's name
    Value:
      Ref: RedshiftCluster
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RedshiftClusterName"
  RedshiftIamCopyRoleArn:
    Description: Redshift IAM copy role ARN
    Value:
        Fn::GetAtt:
          - RedshiftIamCopyRole
          - Arn
  RedshiftSecurityGroup:
    Description: Redshift security group
    Value: !Ref RedshiftSecurityGroup